Html Sanity Check Gradle Plugin
===============================
:version: 0.1.0.SNAPSHOT
:asciidoctor-gradle-plugin-url: TODO http://asciidoctor.org
TODO :issues: https://github.com/gernotstarke/

:asciidoc-url: http://asciidoctor.org
:gradle-url: http://gradle.org/
:gernotstarke: https://github.com/gernotstarke


== About
This plugin provides some basic sanity checking on html files.

It can be helpful in case of html generated from e.g. {asciidoc-url}[Asciidoctor],
Markdown or other formats - as converters usually don't check for missing images
or broken links.


== Installation

Use the following snippet inside a Gradle build file:

.build.gradle
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.aim42:htmlSanityCheck-gradle-plugin:{version}'
    }
}

apply plugin: 'htmlSanityCheck'
----

== Usage

The plugin adds a new task named `sanityCheckHtml`.

This task exposes a single property as part of its configuration

[horizontal]
sourceDir:: where the html file is located. Type: File. Default: `build/docs`.
sourceDocumentName:: an override to process a single source file. Type: File.
Defaults to index.html`

.build.gradle
[source,groovy]
----
// append below the line: apply plugin: 'sanityCheckHtml'

sanityCheckHtml {
    outputDir = new File("$buildDir/docs")
}
----

== Types of Sanity Checks

=== Broken Internal Links

Finds all '<a href="XYZ">' where XYZ is not defined.

.src/broken.html
[source,html]
----
<a href="#missing>internal anchor</a>
...
<h2 id="missinG">Bookmark-Header</h2>
----

TODO: If an anchor XYZ is undefined, the plugin will look for _similar_ definitions
(using a sophisticated string-similarity algorithm).

=== Missing Images


=== Multiple Definitions of Bookmarks or ID's
If any is defined more than once, any anchor linking to it will be confused :-)

== Contributions and Origin
The plugin heavily relies on code provided by the {gradle-url}[Gradle project].

Inspiration on code organization, implementation and testing of the plugin
came from the {asciidoctor-gradle-plugin-url}[Asciidoctor-Gradle-Plugin] by .

Initial implementation by {gernotstarke}[Gernot Starke].